version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: lesson-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - bridge

  php:
    build: .docker/php
    container_name: start-php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - bridge
  db:
    build: .docker/db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql


  adminer:
    build: .docker/adminer
    restart: always
    ports:
      - 6080:8080
networks:
  bridge:
    driver: bridge